// <auto-generated />
using System;
using Firesight.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetTopologySuite.Geometries;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Firesight.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(FiresightDbContext))]
    [Migration("20260906192406_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "postgis");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Firesight.Domain.Wildfires.Wildfire", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Agency")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<double?>("AreaHectares")
                        .HasColumnType("double precision");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("FirstObservedExtinguishedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("LastSeenInFeedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Point>("Location")
                        .IsRequired()
                        .HasColumnType("geography (point)");

                    b.Property<string>("Name")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime?>("StatusDateUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ExternalId")
                        .IsUnique();

                    b.ToTable("Wildfires", (string)null);
                });

            modelBuilder.Entity("Firesight.Infrastructure.Persistence.Sync.CwfisSyncState", b =>
                {
                    b.Property<string>("Source")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("Accepted")
                        .HasColumnType("integer");

                    b.Property<bool>("LastAttemptSucceeded")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("LastAttemptUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastError")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTime?>("LastSuccessfulFetchUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Received")
                        .HasColumnType("integer");

                    b.Property<int>("Rejected")
                        .HasColumnType("integer");

                    b.HasKey("Source");

                    b.ToTable("CwfisSyncState", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
